[package]
name = "matchbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid ={version ="0.8", features = ["serde","v4"]}
rust_decimal = "1.22"
rust_decimal_macros = "1.22"